base:
  project: auto-mpg-project
  random_state: 42
  sep: ','
  encoding: 'utf-8'
  index: False
  target_col: mpg

data_source:
  s3_source: data_given/auto-mpg.csv

load_data:
  raw_dataset_csv: data/raw/auto-mpg.csv

split_data:
  train_path: data/processed/train_auto-mpg.csv
  test_path: data/processed/test_auto-mpg.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.9
      l1_ratio: 0.4
      # alpha: 0.9
      # l1_ratio: 0.4

reports:
  params: report/params.json
  scores: report/scores.json
  indent: 4

save_model:
  model_dir: saved_models
  model_name: model.joblib